repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.20
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: [--group, dev]
